[
   Var                    -- _1,
   Int                    -- _1,
   Uminus                 -- KW["-"] _1,
   Times                  -- _1 KW["*"] _2,
   Plus                   -- _1 KW["+"] _2,
   Minus                  -- _1 KW["-"] _2,
   Eq                     -- _1 KW["="] _2,
   Gt                     -- _1 KW[">"] _2,
   Assign                 -- _1 KW[":="] _2,
   Seq                    -- KW["("] _1 KW[")"],
   Seq.1:iter-star-sep    -- _1 KW[";"],
   If                     -- KW["if"] _1 KW["then"] _2 KW["else"] _3,
   While                  -- KW["while"] _1 KW["do"] _2,
   Let                    -- KW["let"] _1 KW["in"] _2 KW["end"],
   Let.1:iter-star        -- _1,
   Let.2:iter-star-sep    -- _1 KW[";"],
   VarDec                 -- KW["var"] _1 KW[":="] _2,
   FunDecs                -- _1,
   FunDecs.1:iter         -- _1,
   FunDec                 -- KW["function"] _1 KW["("] _2 KW[")"] KW["="] _3,
   FunDec.2:iter-star-sep -- _1 KW[","],
   Call                   -- _1 KW["("] _2 KW[")"],
   Call.2:iter-star-sep   -- _1 KW[","]
]
