[
   Var                 -- _1,
   Int                 -- _1,
   String              -- _1,
   Mul                 -- _1 KW["*"] _2,
   Div                 -- _1 KW["/"] _2,
   Add                 -- _1 KW["+"] _2,
   Sub                 -- _1 KW["-"] _2,
   Equ                 -- _1 KW["="] _2,
   Neq                 -- _1 KW["!="] _2,
   Declaration         -- H hs=0[H[KW["var"] _1] KW[";"]],
   Assign              -- H hs=0[H[_1 KW[":="] _2] KW[";"]],
   Read                -- H hs=0[H[KW["read"] _1] KW[";"]],
   Write               -- H hs=0[H[KW["write"] _1] KW[";"]],
   IfThen              -- V[V is=2[H[KW["if"] _1 KW["then"]] V[_2]] KW["end"]],   
   IfThen.2:iter-star  -- _1,
   IfElse              -- KW["if"] _1 KW["then"] V[_2] KW["else"] V[_3] KW["end"],
   IfElse.2:iter-star  -- _1,
   IfElse.3:iter-star  -- _1,
   While               -- V[V is=2[H[KW["while"] _1 KW["do"]] _2] KW["end"]],
   While.2:iter-star   -- _1,
   For                 -- V[V is=2[H[KW["for"] _1 KW[":="] _2 KW["to"] _3 KW["do"]] _4] KW["end"]],
   For.4:iter-star     -- _1,
   Program             -- V[_1],
   Program.1:iter-star -- _1
]
