#! /bin/sh -e

maakdir() {
  echo "=== Making $1 ========================================"
  cd $1
  ./maak
  cd ..
}

maakdir syn
maakdir sig
maakdir pp
maakdir sim
maakdir renaming
maakdir run
maakdir opt
maakdir til-eblock
maakdir tc
maakdir xmpl

